# System of Linear Equations with a unique solution, Matrix Inverse and the Determinant

The goal of this homework is to learn how to solve systems of linear equations and to be able to compute the determinant and the inverse of an invertible matrix.

**After this assignment you will be able to:**
- Use `NumPy` package to set up the arrays corresponding to the system of linear equations.
- Evaluate the determinant of a matrix and find the solution of the system with `NumPy` linear algebra package.
- Perform row reduction to bring matrix into row echelon form
- Find the solution for the system of linear equations using row reduced approach.
- Compute the inverse of a matrix with `Numpy` linear algebra package and using row reduction approach.

## 1. Solving System of Linear Equations

### 1.1 Row Reduction approach

Solve the following system of linear equations using the reduction method:
$$\begin{cases}
x + 2y - 3z + 4w = 12, \\ 2x + 2y - 2z + 3w = 10, \\ y + z = -1, \\ x - y + z - 2w = -4 \end{cases}\tag{1}$$


In [2]:
import numpy as np
A=np.array([[1,2,-3,4], [2,2,-2,3], [0,1,1,0], [1,-1,1,-2]],dtype=float)
B=np.array([12,10,-1,-4],dtype=float)
aug=np.hstack([A,B.reshape(-1,1)])
n=len(B)
for i in range(n):
    m=i+np.argmax(np.abs(aug[i:,i]))
    aug[[i,m]]=aug[[m,i]]
    for j in range(i+1,n):
        fac=aug[j][i]/aug[i][i]
        aug[j]-=fac*aug[i]
x=np.zeros(n)
for i in range(n-1,-1,-1):
    x[i]=(aug[i,-1]-np.dot(aug[i,i+1:n],x[i+1:]))/aug[i,i]
print(x)

[ 1. -0. -1.  2.]


### 1.2 `Numpy` linear algebra package
Solve the above system of linear equations using the `numpy.linalg` package.

In [3]:
S=np.linalg.solve(A,B)
print(S)

[ 1. -0. -1.  2.]


## 2. Determinant
### 2.1 Compute the determinant of matrix $A$ using the `numpy.linalg` package:

$$ \begin{align}
  \textbf{A}  = \begin{bmatrix}
1 & 0 & -2\\
3 & 1 & -2\\
-5 & -1 & 9
\end{bmatrix}
  \end{align}
  $$

In [4]:
A=np.array([[1,0,-2],[3,1,-2],[-5,-1,9]])
detA=np.linalg.det(A)
print(detA)

3.0000000000000004


### 2.2 Is the above matrix invertible? Why?

Answer here: Since Determinant is 3, the matrix is invertible. For a matrix to be non-invertible, determinant has to be 0.

# 3. Matrix Inverse
### 3.1 Compute the inverse of non-singular matrix $B$ using row reduction
$$ \begin{align}
  \textbf{B}  = \begin{bmatrix}
1 & 2 & 1\\
4 & 4 & 5\\
6 & 7 & 7
\end{bmatrix}
  \end{align}
  $$

In [5]:
import numpy as np
m=np.array([[1,2,1],[4,4,5],[6,7,7]])
i=np.eye(3)
aug=np.hstack([m,i])

for x in range(3):
    val = aug[x,x]
    for y in range(6):
        aug[x,y]= aug[x,y]/val

    for z in range(x+1,3):
        fac = aug[z,x]
        for y in range(6):
            aug[z, y]= aug[z,y]-fac* aug[x,y]
            
for x in range(2,-1,-1):
    for z in range(x-1,-1,-1):
        fac = aug[z,x]
        for y in range(6):
            aug[z,y]= aug[z,y]-fac * aug[x,y]
inv_m = aug[:,3:6]
print(inv_m)


[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


### 3.2 Compute the inverse matrix $B$ using the `numpy.linalg` package.

In [6]:
B=np.array([[1,2,1],[4,4,5],[6,7,7]])
Binv=np.linalg.inv(B)
print(Binv)

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]
